//
//  PrivilegeAndMenu.swift
//  Sleep Disabler
//

import AppKit
import Foundation

enum PrivilegePolicyStatus: Equatable {
    case restricted
    case legacyBroadRule
    case missingOrInvalid
}

final class PrivilegePolicyManager {
    private let runner: CommandRunning
    private let managedPath = "/etc/sudoers.d/sleep_disabler"

    init(runner: CommandRunning = ProcessRunner()) {
        self.runner = runner
    }

    func status() -> PrivilegePolicyStatus {
        // This read-only probe distinguishes the old app-managed unrestricted rule
        // from the current policy, which has no permission for pmset reads via sudo.
        if runner.run(executable: "/usr/bin/sudo", arguments: ["-n", "/usr/bin/pmset", "-g"])?.succeeded == true {
            return .legacyBroadRule
        }
        return allRequiredCommandsAreAllowed() ? .restricted : .missingOrInvalid
    }

    func installOrRepair() -> Bool {
        guard let temporaryRuleURL = writeTemporaryRule() else { return false }
        defer { try? FileManager.default.removeItem(at: temporaryRuleURL) }

        let source = shellQuoted(temporaryRuleURL.path)
        let destination = shellQuoted(managedPath)
        let staging = shellQuoted("\(managedPath).new")
        // The rule is validated before it can replace the app-owned file. `mv` is
        // atomic within /etc/sudoers.d; no other sudoers file is touched.
        let knownManagedFile = "(/usr/bin/grep -Fqx '# Sleep Disabler restricted pmset policy v2' \(destination) || /usr/bin/grep -Fqx '# Sleep Disabler restricted pmset policy v2-exact' \(destination) || /usr/bin/grep -Fqx '%admin ALL=(ALL) NOPASSWD: /usr/bin/pmset' \(destination))"
        let onlyIfManaged = "if [ -e \(destination) ]; then \(knownManagedFile) || exit 42; fi"
        let command = "\(onlyIfManaged) && /usr/sbin/visudo -cf \(source) && /usr/bin/install -o root -g wheel -m 440 \(source) \(staging) && /usr/sbin/visudo -cf \(staging) && /bin/mv -f \(staging) \(destination)"
        return runAdministratorCommand(command)
    }

    private func allRequiredCommandsAreAllowed() -> Bool {
        // Never test a state-changing pmset command at startup. `sudo -l` is a
        // read-only policy query and exposes the individual allowed arguments.
        guard let listing = runner.run(executable: "/usr/bin/sudo", arguments: ["-n", "-l"]), listing.succeeded else {
            return false
        }
        return ["disablesleep", "displaysleep", "sleepnow", "180"].allSatisfy { listing.standardOutput.contains($0) }
    }

    private func supportsSudoersRegularExpressions() -> Bool {
        guard let output = runner.run(executable: "/usr/bin/sudo", arguments: ["--version"])?.standardOutput else { return false }
        guard let line = output.split(separator: "\n").first(where: { $0.lowercased().contains("sudo version") }) else { return false }
        let versionText = line.components(separatedBy: CharacterSet.decimalDigits.inverted).filter { !$0.isEmpty }.joined(separator: ".")
        let parts = versionText.split(separator: ".").compactMap { Int($0) }
        guard parts.count >= 2 else { return false }
        return parts[0] > 1 || (parts[0] == 1 && (parts[1] > 9 || (parts[1] == 9 && (parts.dropFirst(2).first ?? 0) >= 10)))
    }

    private func writeTemporaryRule() -> URL? {
        let url = FileManager.default.temporaryDirectory.appendingPathComponent("sleep_disabler_sudoers_\(UUID().uuidString)")
        do {
            let rule = supportsSudoersRegularExpressions() ? Self.regexRestrictedRule : Self.enumeratedRestrictedRule
            try rule.write(to: url, atomically: true, encoding: .utf8)
            return url
        } catch {
            return nil
        }
    }

    private func runAdministratorCommand(_ command: String) -> Bool {
        // `do shell script … with administrator privileges` uses the standard
        // macOS authorization UI. The command and all paths are app controlled.
        let scriptSource = "do shell script \(appleScriptQuoted(command)) with administrator privileges"
        var error: NSDictionary?
        let result = NSAppleScript(source: scriptSource)?.executeAndReturnError(&error)
        return error == nil && result != nil
    }

    private func shellQuoted(_ value: String) -> String {
        "'\(value.replacingOccurrences(of: "'", with: "'\\\"'\\\"'"))'"
    }

    private func appleScriptQuoted(_ value: String) -> String {
        "\"\(value.replacingOccurrences(of: "\\", with: "\\\\").replacingOccurrences(of: "\"", with: "\\\""))\""
    }

    private static let regexRestrictedRule = """
    # Sleep Disabler restricted pmset policy v2
    # Generated by Sleep Disabler; do not edit this file.
    %admin ALL=(root) NOPASSWD: /usr/bin/pmset ^-a disablesleep [01]$, /usr/bin/pmset ^-a sleep 0$, /usr/bin/pmset ^-a displaysleep 0$, /usr/bin/pmset ^-[bc] (sleep|displaysleep) (0|[1-9][0-9]?|1[0-7][0-9]|180)$, /usr/bin/pmset ^sleepnow$
    """

    // Ventura-era sudo releases can predate sudoers regular-expression support.
    // Enumerating the finite arguments accepted by PowerManager is deliberately
    // verbose, but it keeps the policy exact on those systems as well.
    private static var enumeratedRestrictedRule: String {
        var lines = [
            "# Sleep Disabler restricted pmset policy v2-exact",
            "# Generated by Sleep Disabler; do not edit this file.",
            "%admin ALL=(root) NOPASSWD: /usr/bin/pmset -a disablesleep 0",
            "%admin ALL=(root) NOPASSWD: /usr/bin/pmset -a disablesleep 1",
            "%admin ALL=(root) NOPASSWD: /usr/bin/pmset -a sleep 0",
            "%admin ALL=(root) NOPASSWD: /usr/bin/pmset -a displaysleep 0",
            "%admin ALL=(root) NOPASSWD: /usr/bin/pmset sleepnow"
        ]
        for source in ["-b", "-c"] {
            for setting in ["sleep", "displaysleep"] {
                for value in 0...180 {
                    lines.append("%admin ALL=(root) NOPASSWD: /usr/bin/pmset \(source) \(setting) \(value)")
                }
            }
        }
        return lines.joined(separator: "\n") + "\n"
    }
}

struct MenuBarPresentation {
    let sleepDisabled: Bool
    let lidDimmerEnabled: Bool
    let lidDimmerAvailable: Bool
    let schedulerRunning: Bool
    let schedulerText: String
    let schedulerCanStart: Bool
    let savedDurationText: String
    let menuBarMode: Bool
    let launchAtLoginEnabled: Bool
}

final class MenuBarController: NSObject {
    var onToggleSleep: (() -> Void)?
    var onToggleDimmer: (() -> Void)?
    var onToggleScheduler: (() -> Void)?
    var onShowWindow: (() -> Void)?
    var onToggleMode: (() -> Void)?
    var onToggleLogin: (() -> Void)?
    var onQuit: (() -> Void)?

    private var statusItem: NSStatusItem?

    func update(_ state: MenuBarPresentation) {
        guard state.menuBarMode else { remove() ; return }
        if statusItem == nil { statusItem = NSStatusBar.system.statusItem(withLength: NSStatusItem.variableLength) }
        statusItem?.button?.image = NSImage(systemSymbolName: state.sleepDisabled ? "lock.open.fill" : "lock.fill", accessibilityDescription: "Sleep Disabler")
        let menu = NSMenu()
        add(menu, state.sleepDisabled ? "Enable Sleep" : "Disable Sleep", #selector(toggleSleep))
        menu.addItem(.separator())
        let dimmer = add(menu, state.lidDimmerEnabled ? "Disable Lid Dimmer" : "Enable Lid Dimmer", #selector(toggleDimmer))
        dimmer.isEnabled = state.lidDimmerAvailable
        menu.addItem(.separator())
        if state.schedulerRunning {
            let remaining = NSMenuItem(title: "Sleep Scheduler: \(state.schedulerText) remaining", action: nil, keyEquivalent: "")
            remaining.isEnabled = false
            menu.addItem(remaining)
        }
        let scheduler = add(menu, state.schedulerRunning ? "Stop Sleep Scheduler" : "Start Last Used Sleep Scheduler (\(state.savedDurationText))", #selector(toggleScheduler))
        scheduler.isEnabled = state.schedulerRunning || state.schedulerCanStart
        menu.addItem(.separator())
        add(menu, "Show Window", #selector(showWindow))
        add(menu, state.menuBarMode ? "Switch to Window Mode" : "Switch to Menu Bar Mode", #selector(toggleMode))
        menu.addItem(.separator())
        add(menu, state.launchAtLoginEnabled ? "Disable Login Item" : "Enable Login Item", #selector(toggleLogin))
        menu.addItem(.separator())
        add(menu, "Quit", #selector(quit))
        statusItem?.menu = menu
    }

    func remove() {
        if let statusItem { NSStatusBar.system.removeStatusItem(statusItem) }
        statusItem = nil
    }

    @discardableResult
    private func add(_ menu: NSMenu, _ title: String, _ action: Selector) -> NSMenuItem {
        let item = NSMenuItem(title: title, action: action, keyEquivalent: "")
        item.target = self
        menu.addItem(item)
        return item
    }

    @objc private func toggleSleep() { onToggleSleep?() }
    @objc private func toggleDimmer() { onToggleDimmer?() }
    @objc private func toggleScheduler() { onToggleScheduler?() }
    @objc private func showWindow() { onShowWindow?() }
    @objc private func toggleMode() { onToggleMode?() }
    @objc private func toggleLogin() { onToggleLogin?() }
    @objc private func quit() { onQuit?() }
}
